In [23]:
import pandas as pd
import json

# Function to load JSON lines safely
def load_json_lines(file_path):
    data_list = []
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:  # skip empty lines
                try:
                    data_list.append(json.loads(line))
                except json.JSONDecodeError as e:
                    print(f"Error decoding line: {line[:50]}...")  # show start of problem line
    return pd.DataFrame(data_list)

# Load datasets
reviews_df = load_json_lines(r'C:\Users\gauta\Downloads\Filtered Dataset\filtered_yelp_review.json')
business_df = load_json_lines(r'C:\Users\gauta\Downloads\Filtered Dataset\filtered_yelp_business.json')
users_df = load_json_lines(r'C:\Users\gauta\Downloads\Filtered Dataset\filtered_yelp_user.json')

# Check shapes
print("Reviews:", reviews_df.shape)
print("Business:", business_df.shape)
print("Users:", users_df.shape)

Reviews: (5126287, 5)
Business: (64629, 7)
Users: (1987897, 4)

In [27]:
reviews_business_df = reviews_df.merge(business_df, how='left', on='business_id')
print("Reviews + Business:", reviews_business_df.shape)

Reviews + Business: (5126287, 11)

In [28]:
final_df = reviews_business_df.merge(users_df, how='left', on='user_id')
print("Final merged dataset:", final_df.shape)

Final merged dataset: (5126287, 14)

In [4]:
final_df

,review_id,user_id,business_id,stars_x,text,name_x,stars_y,review_count_x,is_open,attributes,categories,name_y,review_count_y,average_stars
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,"If you decide to eat here, just be aware it is...",Turning Point of North Wales,3.0,169,1,"{'NoiseLevel': 'u'average'', 'HasTV': 'False',...","Restaurants, Breakfast & Brunch, Food, Juice B...",Melanie,33.0,4.06
1,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,Family diner. Had the buffet. Eclectic assortm...,Kettle Restaurant,3.5,47,1,"{'RestaurantsReservations': 'True', 'BusinessP...","Restaurants, Breakfast & Brunch",Debra,1332.0,4.69
2,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,"Wow! Yummy, different, delicious. Our favo...",Zaika,4.0,181,1,"{'Caters': 'True', 'Ambience': '{'romantic': F...","Halal, Pakistani, Restaurants, Indian",Kyle,9.0,4.78
3,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,Cute interior and owner (?) gave us tour of up...,Melt,4.0,32,0,"{'BusinessParking': '{'garage': False, 'street...","Sandwiches, Beer, Wine & Spirits, Bars, Food, ...",Sophia,126.0,2.97
4,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1.0,I am a long term frequent customer of this est...,Dmitri's,4.0,273,0,"{'BusinessParking': '{'garage': False, 'street...","Mediterranean, Restaurants, Seafood, Greek",Q,4.0,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5126282,7NgXAuTFiJHYbuepOPwU0w,x1QLCwZGFAjxRRw4EHc3-g,1_BVWDzi5cVqWxNe9bOMMQ,5.0,Don't misinterpret my 5-star review....I don't...,Wendy's,3.5,55,1,"{'NoiseLevel': 'u'average'', 'BusinessAcceptsC...","Restaurants, Burgers, Food, Fast Food",Samantha,728.0,4.37
5126283,wD5ZWao_vjyT2h4xmGam8Q,7L7GL5Pi2cf8mbm2Dpw4zw,e_E-jq9mwm7wk75k7Yi-Xw,5.0,It is very rare for a restaurant to be this go...,Lark,4.5,23,1,"{'BusinessParking': '{u'valet': False, u'garag...","Bars, Restaurants, American (New), Beer Bar, N...",Ayesha,209.0,3.13
5126284,YVX1Wsa4LYxjvFwuHBb_gA,RKPkxOYQlM0BjhM-H6_vAw,X4mouE_cMiwbfyCPZ_K-FA,4.0,"Good, maybe very good. I went for lunch, so t...",Marhaba,4.0,307,1,"{'GoodForKids': 'True', 'OutdoorSeating': 'Fal...","Halal, Lebanese, Mediterranean, Greek, Restaur...",David,403.0,4.31
5126285,i-I4ZOhoX70Nw5H0FwrQUA,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5.0,For when I'm feeling like ignoring my calorie-...,Sauce on the Side,4.5,83,1,"{'NoiseLevel': 'u'average'', 'WiFi': 'u'free''...","Desserts, Pizza, Salad, Food, Beer, Wine & Spi...",Catherine,281.0,4.14
5126286,RwcKOdEuLRHNJe4M9-qpqg,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3.0,Located in the 'Walking District' in Nashville...,The Pharmacy,4.0,3054,1,"{'OutdoorSeating': 'True', 'RestaurantsGoodFor...","Burgers, Sandwiches, Food, Beer, Wine & Spirit...",Heather,1868.0,3.85

In [5]:
final_df.columns

Index(['review_id', 'user_id', 'business_id', 'stars_x', 'text', 'name_x',
       'stars_y', 'review_count_x', 'is_open', 'attributes', 'categories',
       'name_y', 'review_count_y', 'average_stars'],
      dtype='object')

In [6]:
final_df.isnull().sum()

review_id            0
user_id              0
business_id          0
stars_x              0
text                 0
name_x               0
stars_y              0
review_count_x       0
is_open              0
attributes        8420
categories           0
name_y              11
review_count_y      11
average_stars       11
dtype: int64

In [29]:
columns_to_drop = ['review_id', 'review_count_x', 
                   'review_count_y', 'is_open', 'attributes']

# Drop the columns
ml_df = final_df.drop(columns=columns_to_drop)

In [30]:
ml_df

,user_id,business_id,stars_x,text,name_x,stars_y,categories,name_y,average_stars
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,"If you decide to eat here, just be aware it is...",Turning Point of North Wales,3.0,"Restaurants, Breakfast & Brunch, Food, Juice B...",Melanie,4.06
1,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,Family diner. Had the buffet. Eclectic assortm...,Kettle Restaurant,3.5,"Restaurants, Breakfast & Brunch",Debra,4.69
2,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,"Wow! Yummy, different, delicious. Our favo...",Zaika,4.0,"Halal, Pakistani, Restaurants, Indian",Kyle,4.78
3,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,Cute interior and owner (?) gave us tour of up...,Melt,4.0,"Sandwiches, Beer, Wine & Spirits, Bars, Food, ...",Sophia,2.97
4,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1.0,I am a long term frequent customer of this est...,Dmitri's,4.0,"Mediterranean, Restaurants, Seafood, Greek",Q,2.00
...,...,...,...,...,...,...,...,...,...
5126282,x1QLCwZGFAjxRRw4EHc3-g,1_BVWDzi5cVqWxNe9bOMMQ,5.0,Don't misinterpret my 5-star review....I don't...,Wendy's,3.5,"Restaurants, Burgers, Food, Fast Food",Samantha,4.37
5126283,7L7GL5Pi2cf8mbm2Dpw4zw,e_E-jq9mwm7wk75k7Yi-Xw,5.0,It is very rare for a restaurant to be this go...,Lark,4.5,"Bars, Restaurants, American (New), Beer Bar, N...",Ayesha,3.13
5126284,RKPkxOYQlM0BjhM-H6_vAw,X4mouE_cMiwbfyCPZ_K-FA,4.0,"Good, maybe very good. I went for lunch, so t...",Marhaba,4.0,"Halal, Lebanese, Mediterranean, Greek, Restaur...",David,4.31
5126285,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5.0,For when I'm feeling like ignoring my calorie-...,Sauce on the Side,4.5,"Desserts, Pizza, Salad, Food, Beer, Wine & Spi...",Catherine,4.14
5126286,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3.0,Located in the 'Walking District' in Nashville...,The Pharmacy,4.0,"Burgers, Sandwiches, Food, Beer, Wine & Spirit...",Heather,3.85

In [31]:
ml_df.columns

Index(['user_id', 'business_id', 'stars_x', 'text', 'name_x', 'stars_y',
       'categories', 'name_y', 'average_stars'],
      dtype='object')

In [32]:
!pip install nltk scikit-learn

Requirement already satisfied: nltk in c:\users\gauta\anaconda3\lib\site-packages (3.9.1)
Requirement already satisfied: scikit-learn in c:\users\gauta\anaconda3\lib\site-packages (1.7.1)
Requirement already satisfied: click in c:\users\gauta\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\gauta\anaconda3\lib\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\gauta\anaconda3\lib\site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in c:\users\gauta\anaconda3\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: numpy>=1.22.0 in c:\users\gauta\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.8.0 in c:\users\gauta\anaconda3\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\gauta\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: colorama in c:\users\gauta\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\gauta\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\gauta\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\gauta\anaconda3\Lib\site-packages)

In [33]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Download NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gauta\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\gauta\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\gauta\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [34]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # Lowercase
    text = text.lower()
    
    # Remove punctuation and numbers
    text = re.sub(r'[^a-z\s]', '', text)
    
    # Tokenize and remove stopwords
    tokens = [word for word in text.split() if word not in stop_words]
    
    # Lemmatize
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    
    # Join back to string
    return ' '.join(tokens)

In [35]:
ml_df['clean_text'] = ml_df['text'].apply(preprocess_text)

In [36]:
tfidf = TfidfVectorizer(max_features=5000)  # limit features for speed
X_tfidf = tfidf.fit_transform(ml_df['clean_text'])

print("TF-IDF shape:", X_tfidf.shape)

TF-IDF shape: (5126287, 5000)

In [29]:
X_tfidf

<5126287x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 206248384 stored elements in Compressed Sparse Row format>

In [37]:
def map_sentiment(stars):
    if stars >= 4:
        return 1    # Positive
    elif stars == 3:
        return 0    # Neutral
    else:
        return -1   # Negative

ml_df['sentiment'] = ml_df['stars_x'].apply(map_sentiment)

In [38]:
from sklearn.model_selection import train_test_split

y = ml_df['sentiment']
X = X_tfidf  # TF-IDF features

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

clf = LogisticRegression(max_iter=1000)  # increase iterations if needed
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       0.82      0.85      0.83    209385
           0       0.55      0.32      0.40    116222
           1       0.91      0.96      0.93    699651

    accuracy                           0.87   1025258
   macro avg       0.76      0.71      0.72   1025258
weighted avg       0.85      0.87      0.85   1025258

In [40]:
final_X_tfidf = tfidf.transform(ml_df['clean_text'])
ml_df['sentiment_label'] = clf.predict(final_X_tfidf)

In [41]:
ml_df['sentiment_score'] = ml_df['sentiment_label']

In [42]:
ml_df

,user_id,business_id,stars_x,text,name_x,stars_y,categories,name_y,average_stars,clean_text,sentiment,sentiment_label,sentiment_score
0,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,"If you decide to eat here, just be aware it is...",Turning Point of North Wales,3.0,"Restaurants, Breakfast & Brunch, Food, Juice B...",Melanie,4.06,decide eat aware going take hour beginning end...,0,-1,-1
1,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,Family diner. Had the buffet. Eclectic assortm...,Kettle Restaurant,3.5,"Restaurants, Breakfast & Brunch",Debra,4.69,family diner buffet eclectic assortment large ...,0,1,1
2,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,"Wow! Yummy, different, delicious. Our favo...",Zaika,4.0,"Halal, Pakistani, Restaurants, Indian",Kyle,4.78,wow yummy different delicious favorite lamb cu...,1,1,1
3,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,Cute interior and owner (?) gave us tour of up...,Melt,4.0,"Sandwiches, Beer, Wine & Spirits, Bars, Food, ...",Sophia,2.97,cute interior owner gave u tour upcoming patio...,1,1,1
4,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1.0,I am a long term frequent customer of this est...,Dmitri's,4.0,"Mediterranean, Restaurants, Seafood, Greek",Q,2.00,long term frequent customer establishment went...,-1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5126282,x1QLCwZGFAjxRRw4EHc3-g,1_BVWDzi5cVqWxNe9bOMMQ,5.0,Don't misinterpret my 5-star review....I don't...,Wendy's,3.5,"Restaurants, Burgers, Food, Fast Food",Samantha,4.37,dont misinterpret star reviewi dont think wend...,1,1,1
5126283,7L7GL5Pi2cf8mbm2Dpw4zw,e_E-jq9mwm7wk75k7Yi-Xw,5.0,It is very rare for a restaurant to be this go...,Lark,4.5,"Bars, Restaurants, American (New), Beer Bar, N...",Ayesha,3.13,rare restaurant good category food ambience se...,1,1,1
5126284,RKPkxOYQlM0BjhM-H6_vAw,X4mouE_cMiwbfyCPZ_K-FA,4.0,"Good, maybe very good. I went for lunch, so t...",Marhaba,4.0,"Halal, Lebanese, Mediterranean, Greek, Restaur...",David,4.31,good maybe good went lunch head chef wasnt rev...,1,1,1
5126285,YwAMC-jvZ1fvEUum6QkEkw,Rr9kKArrMhSLVE9a53q-aA,5.0,For when I'm feeling like ignoring my calorie-...,Sauce on the Side,4.5,"Desserts, Pizza, Salad, Food, Beer, Wine & Spi...",Catherine,4.14,im feeling like ignoring caloriecounting indul...,1,1,1
5126286,6JehEvdoCvZPJ_XIxnzIIw,VAeEXLbEcI9Emt9KGYq9aA,3.0,Located in the 'Walking District' in Nashville...,The Pharmacy,4.0,"Burgers, Sandwiches, Food, Beer, Wine & Spirit...",Heather,3.85,located walking district nashville bit way u m...,0,0,0

In [43]:
ml_df.columns

Index(['user_id', 'business_id', 'stars_x', 'text', 'name_x', 'stars_y',
       'categories', 'name_y', 'average_stars', 'clean_text', 'sentiment',
       'sentiment_label', 'sentiment_score'],
      dtype='object')

In [44]:
ml_df['hybrid_score'] = (ml_df['stars_y'] / 5) + (ml_df['sentiment_score'] * 0.3)

In [46]:
ml_df.columns

Index(['user_id', 'business_id', 'stars_x', 'text', 'name_x', 'stars_y',
       'categories', 'name_y', 'average_stars', 'clean_text', 'sentiment',
       'sentiment_label', 'sentiment_score', 'hybrid_score'],
      dtype='object')

In [48]:
# Example: New user wants a hotel in a specific category
def recommend_hotels_new_user(df, category_pref=None, top_n=5):
    """
    Recommend hotels for a new user based on hybrid score.
    
    Parameters:
    df : pandas.DataFrame
        The dataframe containing hotel data and hybrid scores.
    category_pref : str, optional
        Category preference of the user (e.g., 'Luxury', 'Family', 'Budget').
    top_n : int
        Number of hotels to recommend.
    
    Returns:
    pandas.Series : Top N recommended hotels with their average hybrid score
    """
    # Filter by category if specified
    if category_pref:
        filtered_df = df[df['categories'].str.contains(category_pref, na=False)]
    else:
        filtered_df = df.copy()
    
    # Compute average hybrid score per hotel
    hotel_scores = filtered_df.groupby('business_id')['hybrid_score'].mean()
    
    # Sort hotels by score descending
    top_hotels = hotel_scores.sort_values(ascending=False).head(top_n)
    
    return top_hotels

# Example usage
category_preference = "Luxury"  # or None if no preference
top_5_hotels = recommend_hotels_new_user(ml_df, category_pref=category_preference, top_n=5)

print(top_5_hotels)

Series([], Name: hybrid_score, dtype: float64)

In [49]:
def recommend_hotels_new_user_with_names(df, category_pref=None, top_n=5):
    if category_pref:
        filtered_df = df[df['categories'].str.contains(category_pref, na=False)]
    else:
        filtered_df = df.copy()
    
    # Compute average hybrid score per hotel
    hotel_scores = filtered_df.groupby(['business_id', 'name_y'])['hybrid_score'].mean()
    
    # Sort descending and pick top N
    top_hotels = hotel_scores.sort_values(ascending=False).head(top_n)
    
    return top_hotels.reset_index()  # reset_index to see both ID and name

# Example usage
top_5_hotels_named = recommend_hotels_new_user_with_names(ml_df, category_pref="Luxury", top_n=5)
print(top_5_hotels_named)

Empty DataFrame
Columns: [business_id, name_y, hybrid_score]
Index: []

With sentiment(NEw users)

In [92]:
def recommend_hotels_new_user_with_names(df, category_pref=None, top_n=5):
    filtered_df = df.copy()
    
    if category_pref:
        # Filter by category preference (ignore case, skip NaNs)
        filtered_df = filtered_df[filtered_df['categories'].str.contains(category_pref, case=False, na=False)]
        if filtered_df.empty:
            print(f"No hotels found for category: '{category_pref}'")
            return pd.DataFrame(columns=['business_id', 'hotel_name', 'hybrid_score'])
    
    # Aggregate hybrid scores for each hotel
    hotel_scores = (
        filtered_df.groupby(['business_id', 'name_x'])['hybrid_score']
        .mean()
        .reset_index()
        .rename(columns={'name_x': 'hotel_name'})
    )
    
    # Sort by hybrid score
    top_hotels = hotel_scores.sort_values('hybrid_score', ascending=False).head(top_n)
    
    print(f"Top {top_n} hotels recommended:")
    print(top_hotels[['hotel_name', 'hybrid_score']])
    
    return top_hotels

In [93]:
top_5_hotels_named = recommend_hotels_new_user_with_names(ml_df, category_pref="halal", top_n=5)
print(top_5_hotels_named)

Top 5 hotels recommended:
                   hotel_name  hybrid_score
79               Gyro Express           1.3
328  Villekebabs and Platters           1.3
86              Sultan Market           1.3
223                   Eemaani           1.3
13              NY Gyro Lunch           1.3
                business_id                hotel_name  hybrid_score
79   Bze5Vj4MmcE0KHGy346xqw              Gyro Express           1.3
328  trH0bWrq9kwLoLHbvlPKmw  Villekebabs and Platters           1.3
86   CtNglIJY2yp05rZpG9F3tA             Sultan Market           1.3
223  apUqyC9QhujKt4o1Jxl1pA                   Eemaani           1.3
13   0IheZIsRS5tejvxocP18mQ             NY Gyro Lunch           1.3

Without Sentiment(New users)

In [90]:
def recommend_hotels_new_user_no_sentiment(df, category_pref=None, top_n=5):
    filtered_df = df.copy()
    
    if category_pref:
        # Filter by category preference
        filtered_df = filtered_df[filtered_df['categories'].str.contains(category_pref, case=False, na=False)]
        if filtered_df.empty:
            print(f"No hotels found for category: '{category_pref}'. Showing top hotels overall instead.")
            filtered_df = df.copy()
        else:
            print(f"Filtering hotels for category: '{category_pref}'")
    
    # Aggregate ratings and review counts
    hotel_scores = (
        filtered_df.groupby('business_id')
        .agg(average_stars=('average_stars', 'mean'),
            
             hotel_name=('name_x', 'first'))  # Use name_x for actual hotel names
        .reset_index()
    )
    
    # Sort by average rating, then by review count
    top_hotels = hotel_scores.sort_values(['average_stars'], ascending=False).head(top_n)
    
    # Print the top hotels
    print(f"Top {top_n} hotels recommended:")
    print(top_hotels[['hotel_name', 'average_stars']])
    
    return top_hotels

In [91]:
top_5_hotels_named = recommend_hotels_new_user_no_sentiment(ml_df, category_pref="halal", top_n=5)
print(top_5_hotels_named)

Filtering hotels for category: 'halal'
Top 5 hotels recommended:
                       hotel_name  average_stars
223                       Eemaani       4.685000
20           Aavya Indian Cuisine       4.484000
277          The Vegan Halal Cart       4.399167
356           Fattoush Restaurant       4.341111
170  The Original Chicago's Pizza       4.327143
                business_id  average_stars                    hotel_name
223  apUqyC9QhujKt4o1Jxl1pA       4.685000                       Eemaani
20   1BihbEi39AE_nBBdBHwmng       4.484000          Aavya Indian Cuisine
277  kGPCbjR2GiRE8Kdur6QTtA       4.399167          The Vegan Halal Cart
356  zBDQ3eK0jKsP64K_Xx2jgg       4.341111           Fattoush Restaurant
170  U0PcaAwWK478nNwYPklprg       4.327143  The Original Chicago's Pizza

WITH SENTIMENT (Existing)

In [71]:
import pandas as pd

def predict_ratings_with_sentiment(user_id, top_n=5, k=20, alpha=0.7):
    """
    Predict top-N hotels for a user using UBCF + sentiment hybrid score.
    
    Parameters:
    - user_id: the target user
    - top_n: number of hotels to recommend
    - k: number of neighbors in UBCF
    - alpha: weight for UBCF rating (0 < alpha < 1), (1-alpha) is sentiment weight
    
    Returns:
    - DataFrame with top-N recommended hotels
    """
    
    # Step 1: Get predicted ratings from UBCF (all hotels for similar users)
    pred_df = predict_ratings_for_user(user_id, top_n=None, k=k)
    
    if pred_df is None or pred_df.empty:
        return pd.DataFrame(columns=['business_id', 'hotel_name', 'pred_rating', 'sentiment_score', 'hybrid_score'])
    
    # Step 2: Create hotel info mapping (business_id -> hotel name & sentiment)
    hotel_info = ml_df[['business_id','name_x','sentiment_score']].drop_duplicates(subset='business_id')
    hotel_info = hotel_info.rename(columns={'name_x':'hotel_name'})
    
    # Step 3: Merge predicted ratings with hotel info
    pred_df = pred_df.merge(hotel_info, on='business_id', how='left')
    
    # Step 4: Aggregate ratings for each hotel (average if multiple similar users predicted same hotel)
    pred_df = pred_df.groupby(['business_id', 'hotel_name', 'sentiment_score'], as_index=False).agg({'pred_rating':'mean'})
    
    # Step 5: Compute hybrid score
    pred_df['hybrid_score'] = alpha*pred_df['pred_rating'] + (1-alpha)*pred_df['sentiment_score']
    
    # Step 6: Take top-N hotels by hybrid score
    top_hotels_df = pred_df.sort_values('hybrid_score', ascending=False).head(top_n)
    
    return top_hotels_df[['business_id', 'hotel_name', 'pred_rating', 'sentiment_score', 'hybrid_score']]

# Example usage
user_id_example = ml_df['user_id'].iloc[0]
recommendations_hybrid = predict_ratings_with_sentiment(user_id_example, top_n=5, k=20, alpha=0.7)
print(recommendations_hybrid)

                 business_id                 hotel_name  pred_rating  \
1288  jjK2eJS43eMBQEBddYldnA      Guru's Indian Cuisine         35.0
1356  m4s6xuuBnoObBxNmWnkKeg  Thai Tida By Mike & Natta         29.0
541   I8IPPZvEPdb_xG0nGIMyjA  Thai Chef & Noodle Fusion         29.0
70    0zH0l4Jbf-oove3cLvrFOg            Vecchia Osteria         25.0
1119  diovHdArxKlT5ZgkTfDkRQ             Acqua e Farina         19.0

      sentiment_score  hybrid_score
1288                1          24.8
1356                1          20.6
541                 1          20.6
70                 -1          17.2
1119                1          13.6

Without sentiment (Existing Users)

In [72]:
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def ubcf_sparse(user_id, top_n=5, k=20):
    """
    Memory-efficient UBCF recommendation using sparse matrices.
    """
    # Step 1: Encode user and business IDs as integer indices
    users = ml_df['user_id'].unique()
    businesses = ml_df['business_id'].unique()
    user_idx = {user: i for i, user in enumerate(users)}
    business_idx = {b: i for i, b in enumerate(businesses)}

    # Step 2: Build sparse user × hotel matrix
    rows = ml_df['user_id'].map(user_idx).values
    cols = ml_df['business_id'].map(business_idx).values
    data = ml_df['stars_x'].values
    user_hotel_sparse = csr_matrix((data, (rows, cols)), shape=(len(users), len(businesses)))

    # Step 3: Compute cosine similarity for target user only
    if user_id not in user_idx:
        return pd.DataFrame(columns=['business_id', 'hotel_name', 'pred_rating'])
    
    target_idx = user_idx[user_id]
    target_vector = user_hotel_sparse[target_idx]
    
    # Compute similarity only between target user and all others
    sim_scores = cosine_similarity(target_vector, user_hotel_sparse).flatten()
    
    # Step 4: Select top-k similar users
    sim_scores[target_idx] = 0  # ignore self
    top_k_users = np.argsort(sim_scores)[-k:]
    top_k_weights = sim_scores[top_k_users]

    # Step 5: Predict ratings: weighted sum
    top_k_matrix = user_hotel_sparse[top_k_users]
    pred_ratings = top_k_matrix.T.dot(top_k_weights) / (top_k_weights.sum() + 1e-6)  # avoid division by zero

    # Step 6: Remove already rated hotels
    rated_businesses = ml_df[ml_df['user_id'] == user_id]['business_id'].values
    rated_indices = [business_idx[b] for b in rated_businesses if b in business_idx]
    pred_ratings[rated_indices] = 0

    # Step 7: Prepare final DataFrame
    pred_df = pd.DataFrame({
        'business_id': businesses,
        'pred_rating': pred_ratings
    })
    hotel_info = ml_df[['business_id', 'name_x']].drop_duplicates().rename(columns={'name_x': 'hotel_name'})
    pred_df = pred_df.merge(hotel_info, on='business_id', how='left')
    
    # Step 8: Return top-N
    top_hotels = pred_df.sort_values('pred_rating', ascending=False).head(top_n)
    return top_hotels[['business_id', 'hotel_name', 'pred_rating']]

# Example usage
user_id_example = ml_df['user_id'].iloc[0]
ubcf_recs = ubcf_sparse(user_id_example, top_n=5, k=20)
print(ubcf_recs)

                  business_id                 hotel_name  pred_rating
59691  xdG_RW_QsAGJbXp46M_V8w                  MOD Pizza     0.392137
14189  NQ01WqVX0tojNHKn-0sFww       Tir na nOg Irish Pub     0.290582
13575  I8IPPZvEPdb_xG0nGIMyjA  Thai Chef & Noodle Fusion     0.271758
19406  Fs3Iys5SNG5AOiQ_keM79g               Nadia's Thai     0.232466
1675   wUEbysNWCtMSQAio6Ktn6Q  Lucianis Pizzeria & GRILL     0.189183